import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';

const raw = await readFile(new URL('../src/content/wisdom.json', import.meta.url), 'utf8');
const data = JSON.parse(raw);
const entries = data.entries;
const collection = await readFile(new URL('../docs/CONTENT.md', import.meta.url), 'utf8');
const calendar = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31].flatMap((days, month) =>
  Array.from({ length: days }, (_, day) => `${String(month + 1).padStart(2, '0')}-${String(day + 1).padStart(2, '0')}`));
assert.equal(data.version, '0.4');
assert.equal(data.entry_count, 366);
assert.deepEqual(entries.map(entry => entry.date), calendar);
for (const field of ['title', 'body', 'question']) {
  const values = entries.map(entry => entry[field]).filter(value => value !== null);
  assert.equal(new Set(values).size, values.length, `Repeated ${field}`);
  for (const value of values) {
    assert.equal(typeof value, 'string');
    assert.ok(value.length && value === value.trim(), `Blank/padded ${field}`);
    assert.ok(!/[\r\n<>]/.test(value), `Unexpected Markdown/HTML boundary in ${field}`);
    if (field === 'question') assert.ok(value.endsWith('?'));
  }
}
assert.equal(entries.filter(entry => entry.question === null).length, 64);
for (const entry of entries) {
  const rendered = `### ${entry.date}\n\n> [!note] ${entry.title}\n> ${entry.body}`
    + (entry.question ? `\n>\n> *${entry.question}*` : '');
  assert.ok(collection.includes(rendered), `Collection documentation differs from bundled content: ${entry.date}`);
}
const words = text => text.toLowerCase().replace(/[^a-z0-9 ]/g, ' ').split(/\s+/).filter(Boolean);
const lengths = entries.map(entry => words(entry.body).length).sort((a, b) => a - b);
const tokens = entries.map(entry => new Set(words(entry.body)));
const pairs = [];
for (let i = 0; i < entries.length; i++) for (let j = i + 1; j < entries.length; j++) {
  const shared = [...tokens[i]].filter(word => tokens[j].has(word)).length;
  pairs.push({ i, j, score: shared / (tokens[i].size + tokens[j].size - shared) });
}
pairs.sort((a, b) => b.score - a.score);
const table = pairs.slice(0, 7).map(({ i, j, score }) =>
  `| ${entries[i].date} ${entries[i].title} | ${entries[j].date} ${entries[j].title} | ${score.toFixed(3)} |`).join('\n');
const report = `# Content QA — English edition ${data.version}

Generated by \`npm run qa:content\`. Input SHA-256: \`${createHash('sha256').update(raw).digest('hex')}\`.

## Structural checks: passed

- 366 ordered, unique, valid MM-DD entries; February 29 included.
- 366 unique titles and bodies; 302 unique optional questions; 64 null questions.
- Required strings are nonempty, trimmed, and free of line breaks or HTML boundaries.
- Questions end in question marks. Null questions render no prompt section (unit tested).
- Body length: ${lengths[0]}–${lengths.at(-1)} words; median ${lengths[183]} words.
- The source explicitly describes these as original reflections, not historical quotations.
- Every documented date, title, body, and optional question matches the bundled collection.

## Similarity screening

Highest body-word Jaccard similarities (common words included). This is a repeat detector, not a semantic quality score.

| Entry | Entry | Similarity |
| --- | --- | --- |
${table}

## Editorial decisions

Reviewed the seven highest-scoring pairs and the three longest entries for this implementation. The closest pair (April 14 / December 2) addresses requesting help and offering help respectively; retain both. May 28 / December 29 share the theme of self-presentation but distinguish maintaining an image from proving a claim about oneself; retain both. The other screened pairs have distinct situations. The longest entries remain under a minute to read.

The final editorial read-through covered all 366 titles, bodies, and optional questions on 2026-09-24 UTC. Three small wording corrections are recorded in [EDITORIAL_REVIEW.md](EDITORIAL_REVIEW.md). This review checks clarity, tone, and repetition; it is not historical source verification or a guarantee of originality.
`;
await writeFile(new URL('../docs/CONTENT_QA_REPORT.md', import.meta.url), report);
console.log(`Content QA passed: ${entries.length} dates, 302 questions, 64 reflection-only entries.`);
